export {default as Home} from './Home.jsx'
export {default as AboutUs} from './AboutUs.jsx'
export {default as Contact} from './Contact.jsx'
export {default as Services} from './Services.jsx'
export {default as NotFound} from './NotFound.jsx'